Populating footer with data
vegaitsourcing/website-horizont-center pull request #150
Opened 2022-12-03 20:00 UTC by M1K1B

2022-12-04 09:59 UTC, milos1302 requested changes

2022-12-04 09:59 UTC, milos1302 commented on frontend/src/components/footer/footer.jsx
> +              <Image src="/images/youtubeWhite.svg" width="30" height="30" alt="link to our youtube" />
`youtubeWhite.svg` i `youtubeBlue.svg` sam ja ubacio, ali sad vidim da im naziv nije u skladu sa ostalim nazivima za ikonice drustvenih mreza 😁
Kad vec radis na ovome, da li mozes da ispravis te nazive u:
- `youtubeIconWhite.svg`
- `youtubeIconBlue.svg`

2022-12-04 09:59 UTC, milos1302 commented on frontend/src/components/footer/footer.jsx
> +  );
Vidim da nema nikakvih izmena u `.scss` fajlovima... 
U dokumentu u kojem se nalaze novi zahtevi, pise da linkove treba raspodeliti u 2 kolone, a nas trenutni kod dozvoljava da se ti linkovi raspodele i u 4 kolone (u zavisnosti od sirine ekrana). 
Najmanji broj kolona koje nas trenutni kod dozvoljava je 2 i treba samo taj broj iz dinamickog pretvoriti u fiksni, tj. da uvek bude 2 kolone bez obzira kolika je sirina ekrana. 
Mozes i u potpunosti izmeniti SCSS koji se odnosi na taj deo footer-a, sve dok odgovara tim novim zahtevima.
Ti novi zahtevi su: 2 kolone, gde svaka kolona ima navedene item-e koje u sebi treba da ima i redosled tih item-a. 
To znaci da neces moci koristiti `navigationItems.map`. 
Jedno od resenja bi bilo da svaki item u `navigationItems` izdvojis u zaseban objekat i reference thih objekata ubacis u `navigationItems` listu. 
Primer item objekta: 
```
export const HOME_NAV_ITEM = {
		name: "Zajednica",
		pathname: HOME_PATHNAME,
		active: true,
	}
```
Refaktorisana `navigationItems` lista:
``` 
export const navigationItems = [
    HOME_NAV_ITEM,
    CAREGIVERS_NAV_ITEM,
    ...
]
```
Ovo ti omogucava da u `footer.jsx` (ili bilo kojem drugom fajlu) kreiras specificnu listu nav item-a, sa drugacijim brojem i redosledom. U tvom slucaju, trebaju ti dve liste (leva i destna kolona).

2022-12-04 12:09 UTC, M1K1B commented on frontend/src/components/footer/footer.jsx
> +              <Image src="/images/youtubeWhite.svg" width="30" height="30" alt="link to our youtube" />
Naravno 😀

2022-12-05 08:29 UTC, milos1302 approved these changes

2022-12-05 08:29 UTC, merged